# Generated by Django 2.0.13 on 2019-07-25 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20170217_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(db_index=True)),
                ('rate_value', models.DecimalField(db_index=True, decimal_places=6, max_digits=18)),
                ('exchanged_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversed_exchanges', to='exchange_rates.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.Category')),
                ('adapter', models.CharField(choices=[('FIXER', 'exchange_rates.backends.fixer.FixerExchangeProviderBackend'), ('MOCK', 'exchange_rates.backends.mock.MockExchangeProviderBackend')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Providers',
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('categories.category',),
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_rates.Provider'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='source_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='exchange_rates.Currency'),
        ),
    ]
